### ISSUE TITLE
Designing Class Diagram: Profile

### ISSUE THREAD

**Issue by zeynep-baydemir** [bounswe/bounswe2023group5#49]
### Description

The class diagrams are shared among the team members, I will design the class diagram of profile.

### 👮‍♀️ Reviewer

Can Uzduran

### ⏰ Deadline

07.04.2023

**Comment by canuzdrn** [comment]
- I think having setter methods instead of real-world type method names would be more suitable for OOP design. For example you may change the **change_profile_photo()** method's name to **set_profile_photo()** and same thing can be applied to **change_privacy()**. It's not a huge or critical issue, yet important when we're going to be using method of classes in our code.

Otherwise, good work and nicely designed !

**Comment by zeynep-baydemir** [comment]
Thank you, I have changed those methods.

**Comment by canuzdrn** [comment]
There is nothing more to be added on my side, thanks for the good work !
Since @zeynep-baydemir is done with class diagram of **Profile**, I'm closing this issue
