### ISSUE TITLE
Designing Use Case Diagram: Forum

### ISSUE THREAD

**Issue by halisbal** [bounswe/bounswe2023group5#61]
### Description

The use case diagrams are shared among the team members, I will design the use case diagram of Forum. 

### 👮‍♀️ Reviewer

Can Uzduran

### ⏰ Deadline

08.04.2023 - Saturday - 23.59

**Comment by canuzdrn** [comment]
- There exist a bidirectional arrow between "Forum" and "Commenting", I'm not sure that is done purposefully or not (where bidirectional arrow means bidirectional association which may not be the case for Forum-Commenting relation)
- You may enlarge the shape of usecases you've used at the very right of the diagram, in order to increase readability
- Some of the **includes** statements went through shapes of use cases (ellipsis), not a critical problem but you may arrange these texts in order to increase readability
- I'm okay with the categorization, it seems organized
Otherwise, nice work !

**Comment by halisbal** [comment]
Thank you for your feedback! I updated the use case diagram based on your thoughts. Can you check it again? @canuzdrn

**Comment by canuzdrn** [comment]
It's looking better now, thanks for your good work and I appreciate that you are evaluated my and other team member's feedback about the use case diagram of forum. Since, you are done with use case diagram of forum, I'm closing this issue.
