### ISSUE TITLE
Designing Use Case Diagram: Post/Comment 

### ISSUE THREAD

**Issue by UnalDeniz** [bounswe/bounswe2023group5#62]
### Description

The use case diagrams are shared among the team members, I will design the use case diagram related to posts and comments that are a part of forum diagrams.

### 👮‍♀️ Reviewer

Halis Bal

### ⏰ Deadline

2023-04-08 Saturday 23.59

**Comment by halisbal** [comment]
Since I was responsible for use case diagram of Forum (#61 ) and forum, post, comment logics are very close to each other, we designed them as a one use case diagram together with @UnalDeniz . Therefore I was able to review his work closely. The work is also reviewed by @canuzdrn in my issue, so I believe that this task is done. Good work! @UnalDeniz. Since you are done, I am closing this issue.
