### ISSUE TITLE
A  summary of the customer feedback and reflections

### ISSUE THREAD

**Issue by alperen-bircak** [bounswe/bounswe2023group5#783]
### Description

A  summary of the customer feedback and reflections is required for Milestone 2.

### 👮‍♀️ Reviewer

None

### ⏰ Deadline

31.11.2023

**Comment by halisbal** [comment]
I prepared the summary of the customer feedback and reflections part for the milestone report, and added it to the wiki page that we created. [Here](https://github.com/bounswe/bounswe2023group5/wiki/CMPE-451-Milestone-2-Report#2-customer-feedback-and-reflections) you can reach to the milestone report. Since this task is done, I am closing this issue.
